# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
  profile = "prd-profile"

  assume_role {
    role_arn = "arn:aws:iam::5123456789012:role/TerraformRole"
  }
}
